library(org.Hs.eg.db)
library(AnnotationDbi)
library(readxl)
data=readRDS("C:/Users/91735/Documents/BVP material/7_cancer genomics/DEG_data.rds")
head(data)
dim(data)
ensl=rownames(data)
gen=rownames(data)
ens_id <- gsub("\\.[0-9]*$", "", gen)
ens_id  
data$gene_symbol<-mapIds(org.Hs.eg.db,keys=ens_id,keytype = "ENSEMBL",column = "SYMBOL")
head(data)
library(dplyr)
data=data %>% select(gene_symbol,everything())
head(data)
library(tidyr)
data1=data %>% drop_na()
head(data1)
dim(data1)
write.csv(data1,file="C:/Users/91735/Documents/BVP material/7_cancer genomics/Enhanced_DEG.csv")
#V=readRDS("C:/Users/91735/Documents/BVP material/7_cancer genomics/Enhanced_DEG.csv")
#rownames(V)=make.names(V[,1],unique = TRUE)
#V=V[,-1]
View(V)
